Fixed cfsp script to work for both local and pip install. Added simple readme for pypi.

diff --git a/cfsp b/cfsp
--- a/cfsp
+++ b/cfsp
@@ -24,9 +24,21 @@
 #  *     Description:
 #  *       Bash script to invoke the cFSP tool
 #  *
-
 export cFsysPy3_cmd_hint_0=$(hash -d python3.8 2>>/dev/null; which python3.8 2>>/dev/null || echo "failed")
 export cFsysPy3_cmd_hint_1=$(hash -d python3   2>>/dev/null; which python3   2>>/dev/null || echo "failed")
 
-source cfenv/bin/activate
-python3 ./cFSPlib/cFSP.py "$@"
+if [ -f cfenv/bin/activate ]; then
+    source cfenv/bin/activate
+fi
+#export cfsp_path=$((pip show cfsp | grep "Location:" | cut -d " " -f2) || echo "failed")
+#cfsp_path = os.path.dirname(os.path.abspath(__file__))+"../lib/python3.8/site-packages/cFSPlib"
+export cfsp_path=$(readlink -f $0)
+export cfsp_dir="`dirname $cfsp_path`/../lib/python*/site-packages"
+echo $cfsp_dir
+
+# If cfsp is installed through pip, it should be located in the former path, else, if it is installed through git, it is just located in the current folder of cFSPlib.
+if [ -d $cfsp_dir ]; then
+	python3 $cfsp_dir/cFSPlib/cFSP.py "$@"
+else
+	python3 ./cFSPlib/cFSP.py "$@"
+fi
